version: '3.8'

services:
  backend:
    env_file: .env
    image: node:16
    container_name: backend_weather
    restart: always
    working_dir: /app
    volumes:
       - ./src:/app/src
       - ./package.json:/app/package.json
       - ./package-lock.json:/app/package-lock.json
       - ./seed:/app/seed
    command: bash -c "npm install && npm run seed && npm run dev"
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    networks:
      - nt_weather
  db: 
    container_name: db_weather
    env_file: .env
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
        - ${PORT_DB}:${PORT_DB}
    volumes:
        - ./db:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - nt_weather

networks:
   nt_weather:
     name: nt_weather
